add search test
vdemnyk/protractor-project pull request #5
Opened 2021-05-11 06:58 UTC by vdemnyk

2021-05-11 07:34 UTC, nbabii requested changes

2021-05-11 07:34 UTC, nbabii commented on pages/product.page.js
> +let baseElementLocator = by.css('[name="back"]');
Please use locator which will be on product details page onlly

2021-05-11 07:34 UTC, nbabii commented on pages/search.page.js
> +        let number = text[0];
this will not work if you have a two-digit number, please parse the number from the string (should work with any number lenght)

2021-05-11 07:34 UTC, nbabii commented on pages/search.page.js
> +    async clickOnProduct() {
please make this method to be reusable, to click any product using the product index (by position in the result list)

2021-05-12 19:56 UTC, vdemnyk commented on pages/product.page.js
> +let baseElementLocator = by.css('[name="back"]');
Done

2021-05-12 19:56 UTC, vdemnyk commented on pages/search.page.js
> +        let number = text[0];
Done

2021-05-12 19:56 UTC, vdemnyk commented on pages/search.page.js
> +    async clickOnProduct() {
Done

2021-05-13 12:02 UTC, nbabii requested changes

2021-05-13 12:02 UTC, nbabii commented on pages/search.page.js
> +        return parseInt(await this.getResultElement().getText());
Check if works properly, if not use RegEx to parse digit

2021-05-13 12:02 UTC, nbabii commented on pages/search.page.js
> +            let productLocator = by.css(`ul.product_list>:nth-of-type(${listItem}) .product-name`);
please use object cloning here

2021-05-16 18:24 UTC, vdemnyk commented on pages/search.page.js
> +        return parseInt(await this.getResultElement().getText());
Works fine, returns the number

2021-05-16 18:25 UTC, vdemnyk commented on pages/search.page.js
> +            let productLocator = by.css(`ul.product_list>:nth-of-type(${listItem}) .product-name`);
Done

2021-05-18 06:32 UTC, merged